<div class="mx-auto max-w-5xl space-y-6">
    <section class="rounded-2xl border border-stone-200 bg-[#fbf8f2] p-5 sm:p-7">
        <div class="flex flex-col justify-between gap-5 sm:flex-row sm:items-start">
            <div><p class="font-mono text-xs font-semibold uppercase tracking-[0.18em] text-emerald-700">Plan & Billing</p><h1 class="mt-2 text-2xl font-semibold text-stone-900">{{ $active ? (($latest?->status?->value === 'trial') ? 'Trial' : ucfirst($latest?->plan?->value ?? 'Premium')) : 'Free Plan' }}</h1><p class="mt-1 text-sm text-stone-500">Your entitlement access and current subscription status.</p></div>
            <span class="rounded-full bg-{{ $active ? 'emerald' : 'stone' }}-100 px-3 py-1 text-xs font-semibold capitalize text-{{ $active ? 'emerald' : 'stone' }}-800">{{ $active ? ($latest?->status?->value ?? 'active') : 'free' }}</span>
        </div>
        @if ($latest)
            <dl class="mt-6 grid gap-4 border-t border-stone-200 pt-5 text-sm sm:grid-cols-3"><div><dt class="text-stone-500">Started</dt><dd class="mt-1 font-medium text-stone-800">{{ $latest->starts_at?->format('d M Y') }}</dd></div><div><dt class="text-stone-500">Expires</dt><dd class="mt-1 font-medium text-stone-800">{{ $latest->expires_at?->format('d M Y') ?? 'No expiry' }}</dd></div><div><dt class="text-stone-500">Days remaining</dt><dd class="mt-1 font-medium text-stone-800">{{ $daysRemaining === null ? '—' : max(0, $daysRemaining) }}</dd></div></dl>
            @if ($active && $daysRemaining !== null && $daysRemaining >= 0 && $daysRemaining <= 7)<p class="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">Your subscription expires in {{ $daysRemaining }} days.</p>@elseif (! $active)<p class="mt-5 rounded-xl border border-stone-200 bg-white/60 p-3 text-sm text-stone-600">Your Premium subscription expired or was cancelled. You are currently using the Free plan.</p>@endif
        @endif
        @if (! $active)<button type="button" x-data @click="$dispatch('show-upgrade')" class="mt-6 rounded-xl bg-emerald-700 px-4 py-2.5 text-sm font-semibold text-white hover:bg-emerald-800">Upgrade to Premium</button>@endif
    </section>
    <section><h2 class="text-lg font-semibold text-stone-900">Usage this period</h2><div class="mt-3 grid gap-3 sm:grid-cols-2">@foreach ($usage as $name => $item)<article class="rounded-2xl border border-stone-200 bg-[#fbf8f2] p-4"><div class="flex justify-between gap-3"><h3 class="text-sm font-semibold capitalize text-stone-800">{{ str_replace('_', ' ', $name) }}</h3><span class="font-mono text-sm text-stone-600">{{ $item['limit'] === null ? 'Unlimited' : $item['usage'].' / '.$item['limit'] }}</span></div>@if ($item['limit'] !== null)<div class="mt-3 h-2 rounded-full bg-stone-200"><div class="h-2 rounded-full bg-emerald-600" style="width: {{ min(100, ($item['usage'] / max(1, $item['limit'])) * 100) }}%"></div></div>@endif</article>@endforeach</div></section>
    <section class="rounded-2xl border border-stone-200 bg-[#fbf8f2] p-5"><h2 class="text-lg font-semibold text-stone-900">Free and Premium</h2><div class="mt-4 grid gap-5 md:grid-cols-2"><div><h3 class="font-semibold text-stone-800">Free</h3><ul class="mt-2 space-y-1 text-sm text-stone-600"><li>Up to {{ $free['accounts']['limit'] }} accounts</li><li>Up to {{ $free['recurring_transactions']['limit'] }} recurring schedules</li><li>{{ $free['ai_insights']['limit'] }} AI analyses/month</li><li>{{ $free['receipt_scanner']['limit'] }} receipt scans/month</li><li>Basic financial analytics, transactions, transfers and categories</li></ul></div><div><h3 class="font-semibold text-emerald-800">Premium</h3><ul class="mt-2 space-y-1 text-sm text-stone-600"><li>Unlimited accounts and recurring schedules</li><li>Unlimited AI analyses and receipt scans</li><li>Advanced analytics</li><li>All core financial functionality</li></ul></div></div></section>
    <div x-data="{ open: false }" @show-upgrade.window="open = true" x-show="open" x-cloak class="fixed inset-0 z-50 flex items-center justify-center bg-stone-900/30 p-4"><div @click.outside="open = false" class="w-full max-w-md rounded-2xl border border-stone-200 bg-[#fbf8f2] p-6 shadow-xl"><h2 class="text-lg font-semibold text-stone-900">Upgrade to Premium</h2><p class="mt-2 text-sm text-stone-600">Choose a plan and mobile-money method. Payment activation is completed after provider confirmation.</p><form wire:submit="beginPayment" class="mt-4 space-y-3"><select wire:model="plan" class="w-full rounded-xl border-stone-300 bg-white"><option value="monthly">Monthly</option><option value="annual">Annual</option></select><select wire:model="paymentMethod" class="w-full rounded-xl border-stone-300 bg-white"><option value="mtn_momo">MTN Mobile Money</option><option value="orange_money">Orange Money</option></select><input wire:model="phone" type="tel" placeholder="Cameroon mobile number" class="w-full rounded-xl border-stone-300 bg-white"><button type="submit" wire:loading.attr="disabled" class="rounded-xl bg-emerald-700 px-4 py-2 text-sm font-semibold text-white">Start payment</button></form>@if ($paymentMessage)<p class="mt-3 text-sm text-emerald-700">{{ $paymentMessage }}</p>@endif<button type="button" @click="open = false" class="mt-5 rounded-xl border border-stone-300 px-4 py-2 text-sm font-semibold text-stone-700">Close</button></div></div>
</div>
