<form wire:submit="save" class="space-y-5">
    <fieldset><legend class="mb-2 text-sm font-semibold text-stone-800">Type</legend><div class="grid grid-cols-2 gap-2">@foreach (['expense' => 'Expense', 'income' => 'Income'] as $value => $label)<label class="cursor-pointer"><input type="radio" wire:model.live="type" value="{{ $value }}" class="peer sr-only"><span class="block rounded-xl border border-stone-200 px-4 py-3 text-center text-sm font-semibold text-stone-600 peer-checked:border-emerald-700 peer-checked:bg-emerald-50 peer-checked:text-emerald-800">{{ $label }}</span></label>@endforeach</div>@error('type') <p class="mt-1 text-xs text-red-600">{{ $message }}</p> @enderror</fieldset>
    <div class="grid gap-4 sm:grid-cols-2">
        <label><span class="mb-1.5 block text-sm font-medium text-stone-700">Account</span><select wire:model="accountId" class="w-full rounded-xl border-stone-200 bg-white/60 text-sm"><option value="">Select an account</option>@foreach ($accounts as $account)<option value="{{ $account->id }}">{{ $account->name }} — {{ number_format($account->current_balance, 0) }} {{ $account->currency }}</option>@endforeach</select>@error('accountId') <p class="mt-1 text-xs text-red-600">{{ $message }}</p> @enderror</label>
        <label><span class="mb-1.5 block text-sm font-medium text-stone-700">Category</span><select wire:model.live="categoryId" class="w-full rounded-xl border-stone-200 bg-white/60 text-sm"><option value="">Select a category</option>@foreach ($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select>@error('categoryId') <p class="mt-1 text-xs text-red-600">{{ $message }}</p> @enderror</label>
    </div>
    <label class="block"><span class="mb-1.5 block text-sm font-medium text-stone-700">Title</span><input type="text" wire:model="title" class="w-full rounded-xl border-stone-200 bg-white/60 text-sm">@error('title') <p class="mt-1 text-xs text-red-600">{{ $message }}</p> @enderror</label>
    <div class="grid gap-4 sm:grid-cols-3"><label><span class="mb-1.5 block text-sm font-medium text-stone-700">Amount</span><input type="number" min="0" step="0.01" wire:model.live.debounce.300ms="amount" class="w-full rounded-xl border-stone-200 bg-white/60 text-sm">@error('amount') <p class="mt-1 text-xs text-red-600">{{ $message }}</p> @enderror</label><label><span class="mb-1.5 block text-sm font-medium text-stone-700">Date</span><input type="date" wire:model.live="date" class="w-full rounded-xl border-stone-200 bg-white/60 text-sm">@error('date') <p class="mt-1 text-xs text-red-600">{{ $message }}</p> @enderror</label><label><span class="mb-1.5 block text-sm font-medium text-stone-700">Status</span><select wire:model.live="status" class="w-full rounded-xl border-stone-200 bg-white/60 text-sm"><option value="completed">Completed</option><option value="pending">Pending</option></select></label></div>
    @if ($budgetAvailability)
        @php($shortfall = max((float) $amount - (float) $budgetAvailability['remaining'], 0))
        <aside class="rounded-xl border border-stone-200 bg-stone-50 p-4 text-sm">
            <div class="flex items-center justify-between gap-3"><p class="font-semibold">{{ $budgetAvailability['category_name'] }} Budget</p><p class="font-mono font-bold">{{ number_format($budgetAvailability['limit'], 0) }} FCFA</p></div>
            <div class="mt-2 flex gap-4 text-xs text-stone-500"><span>Spent: {{ number_format($budgetAvailability['spent'], 0) }} FCFA</span><span>Remaining: {{ number_format($budgetAvailability['remaining'], 0) }} FCFA</span></div>
            @if ($shortfall > 0)
                <p class="mt-3 rounded-lg bg-red-50 p-2 text-xs font-medium text-red-700">This expense exceeds the remaining {{ $budgetAvailability['category_name'] }} budget by {{ number_format($shortfall, 0) }} FCFA.</p>
            @endif
        </aside>
    @endif
    <label class="block"><span class="mb-1.5 block text-sm font-medium text-stone-700">Description (optional)</span><textarea wire:model="description" rows="3" class="w-full rounded-xl border-stone-200 bg-white/60 text-sm"></textarea></label>
    <div class="flex flex-col-reverse gap-2 border-t border-stone-200 pt-5 sm:flex-row sm:justify-end"><a href="{{ route('transactions') }}" class="rounded-xl border border-stone-300 px-4 py-2.5 text-center text-sm font-semibold text-stone-700">Cancel</a><button type="submit" wire:loading.attr="disabled" wire:target="save" class="rounded-xl bg-emerald-700 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60"><span wire:loading.remove wire:target="save">{{ $submitLabel }}</span><span wire:loading wire:target="save">Saving...</span></button></div>
</form>
