<div class="space-y-7 transition-opacity duration-200" wire:loading.class="opacity-60">
    <section><a href="{{ route('accounts') }}" class="text-sm font-medium text-stone-500 hover:text-emerald-700">&larr; Accounts</a><div class="mt-4 flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div class="flex flex-wrap items-center gap-2"><h1 class="text-2xl font-semibold tracking-tight text-stone-900 sm:text-3xl">{{ $account->name }}</h1>@if ($account->is_default)<span class="rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wider text-emerald-700">Default</span>@endif</div><p class="mt-1 text-sm text-stone-500">{{ $account->type->label() }}</p></div><div class="flex gap-2"><a href="{{ route('accounts.edit', $account) }}" class="rounded-xl border border-stone-300 px-4 py-2.5 text-center text-sm font-semibold text-stone-700">Edit</a><div class="relative" x-data="{ open: false }" @click.outside="open = false"><button type="button" @click="open = ! open" class="flex h-10 w-10 items-center justify-center rounded-xl border border-stone-300 text-stone-600 hover:bg-stone-100" aria-label="Account actions"><span aria-hidden="true">•••</span></button><div x-cloak x-show="open" class="absolute right-0 z-40 mt-2 w-44 rounded-xl border border-stone-200 bg-[#fbf8f2] p-1.5 shadow-lg">@unless($account->is_default)<button type="button" wire:click="setDefault" @click="open = false" class="block w-full rounded-lg px-3 py-2 text-left text-sm text-stone-700 hover:bg-stone-100">Set as default</button>@endunless<div class="my-1 border-t border-stone-200"></div><button type="button" wire:click="confirmDeletion" @click="open = false" class="block w-full rounded-lg px-3 py-2 text-left text-sm font-medium text-red-700 hover:bg-red-50">Delete account</button></div></div></div></div></section>
    <section class="grid gap-4 lg:grid-cols-3"><article class="rounded-2xl border border-stone-200 bg-[#fbf8f2] p-6 lg:col-span-2"><p class="text-xs font-semibold uppercase tracking-wider text-stone-500">Current Balance</p><p class="mt-5 font-mono text-3xl font-bold {{ $account->current_balance < 0 ? 'text-red-700' : 'text-stone-900' }} sm:text-4xl">{{ number_format($account->current_balance, 0) }}</p><p class="mt-1 text-sm text-stone-500">{{ $account->currency }}</p></article><article class="rounded-2xl border border-stone-200 bg-[#fbf8f2] p-5"><h2 class="text-sm font-semibold text-stone-900">Account Information</h2><dl class="mt-4 space-y-3 text-sm">@foreach (['Account type' => $account->type->label(), 'Currency' => $account->currency, 'Opening balance' => number_format($account->opening_balance, 0).' '.$account->currency, 'Current balance' => number_format($account->current_balance, 0).' '.$account->currency, 'Default status' => $account->is_default ? 'Default' : 'Not default'] as $label => $value)<div class="flex justify-between gap-4"><dt class="text-stone-500">{{ $label }}</dt><dd class="text-right font-medium text-stone-800">{{ $value }}</dd></div>@endforeach</dl></article></section>
    <section><div class="mb-4 flex items-center gap-3"><h2 class="font-mono text-xs font-semibold uppercase tracking-[0.18em] text-stone-500">Recent Activity</h2><div class="flex-1 border-t border-dashed border-stone-300"></div><a href="{{ route('transactions', ['account' => $account->id]) }}" class="text-xs font-semibold text-emerald-700">View all</a></div><div class="rounded-2xl border border-stone-200 bg-[#fbf8f2]">@forelse($transactions as $transaction)@php($income = $transaction->type->isIncome())<article class="grid grid-cols-[1fr_auto] gap-x-4 gap-y-1 border-b border-stone-200 px-4 py-3.5 last:border-0 sm:px-5"><p class="truncate text-sm font-semibold text-stone-900">{{ $transaction->title }}</p><p class="font-mono text-sm font-bold {{ $income ? 'text-emerald-700' : 'text-red-700' }}">{{ $income ? '+' : '−' }}{{ number_format($transaction->amount, 0) }} {{ $account->currency }}</p><p class="truncate text-xs text-stone-500">{{ $transaction->category?->name ?? ($transaction->transfer_id ? 'Transfer' : 'Uncategorized') }}</p><time class="text-right text-xs text-stone-500">{{ $transaction->date->format('d M Y') }}</time></article>@empty<div class="px-6 py-10 text-center"><p class="text-sm font-semibold text-stone-800">No transactions for this account yet.</p><p class="mt-1 text-xs text-stone-500">Transactions using this account will appear here.</p></div>@endforelse</div>@if($transactions->hasPages())<div class="mt-5">{{ $transactions->links() }}</div>@endif</section>
    @if ($confirmingDeletion)
        <div class="fixed inset-0 z-50 flex items-center justify-center bg-stone-950/40 p-4" role="dialog" aria-modal="true" aria-labelledby="delete-account-title">
            <div class="w-full max-w-md rounded-2xl border border-stone-200 bg-[#fbf8f2] p-6 shadow-xl">
                <h2 id="delete-account-title" class="text-lg font-semibold text-stone-900">Delete account?</h2>
                <p class="mt-2 text-sm text-stone-600">You're about to permanently delete:</p>
                <div class="mt-4 rounded-xl border border-stone-200 bg-white/60 p-4"><p class="font-semibold text-stone-900">{{ $account->name }}</p><p class="mt-1 font-mono text-sm text-stone-700">{{ number_format($account->current_balance, 0) }} {{ $account->currency }}</p></div>
                <p class="mt-4 text-xs text-stone-500">This action is only possible if the account has no financial history.</p>
                @if ($account->current_balance != 0)<p class="mt-2 text-xs text-amber-700">Deleting this account will remove its balance from your tracked total. No transfer will be created.</p>@endif
                @if ($deletionError)<p class="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{{ $deletionError }}</p>@endif
                <div class="mt-6 flex justify-end gap-2"><button type="button" wire:click="$set('confirmingDeletion', false)" class="rounded-xl border border-stone-300 px-4 py-2.5 text-sm font-semibold text-stone-700">Cancel</button><button type="button" wire:click="delete" wire:loading.attr="disabled" wire:target="delete" class="rounded-xl bg-red-700 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60"><span wire:loading.remove wire:target="delete">Delete account</span><span wire:loading wire:target="delete">Deleting...</span></button></div>
            </div>
        </div>
    @endif
</div>
