<div class="space-y-7" wire:loading.class="opacity-60">
    <section class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="font-mono text-xs font-semibold uppercase text-emerald-700">Organization</p><h1 class="text-3xl font-semibold">Categories</h1><p class="text-sm text-stone-500">Organize your income and expenses.</p></div><a href="{{ route('categories.create') }}" class="rounded-xl bg-emerald-700 px-4 py-2.5 text-center text-sm font-semibold text-white">+ Add Category</a></section>
    <section class="flex gap-2 rounded-2xl border border-stone-200 bg-[#fbf8f2] p-2"><button wire:click="setType('expense')" class="flex-1 rounded-xl p-2.5 text-sm font-semibold {{ $selectedType->isExpense()?'bg-red-50 text-red-700':'text-stone-500' }}">Expense · {{ $counts['expense'] }}</button><button wire:click="setType('income')" class="flex-1 rounded-xl p-2.5 text-sm font-semibold {{ $selectedType->isIncome()?'bg-emerald-50 text-emerald-700':'text-stone-500' }}">Income · {{ $counts['income'] }}</button></section>
    <section><div class="mb-4 flex items-center gap-3"><h2 class="font-mono text-xs font-semibold uppercase text-stone-500">{{ $selectedType->label() }} Categories</h2><div class="flex-1 border-t border-dashed border-stone-300"></div></div>
        @if($categories->isEmpty())<div class="rounded-2xl border border-dashed border-stone-300 bg-[#fbf8f2] p-10 text-center"><h3 class="font-semibold">No {{ $selectedType->value }} categories</h3><p class="mt-1 text-sm text-stone-500">Create categories to organize your {{ $selectedType->isExpense()?'spending':'income' }}.</p><a href="{{ route('categories.create',['type'=>$selectedType->value]) }}" class="mt-5 inline-flex rounded-xl bg-emerald-700 px-4 py-2.5 text-sm font-semibold text-white">Add {{ $selectedType->label() }} Category</a></div>
        @else<div class="rounded-2xl border border-stone-200 bg-[#fbf8f2]">@foreach($categories as $category)<article class="flex items-center gap-3 border-b border-stone-200 px-4 py-3.5 last:border-0"><span class="flex h-10 w-10 items-center justify-center rounded-xl text-sm font-bold text-white" style="background:{{ preg_match('/^#[0-9a-fA-F]{6}$/',(string)$category->color)?$category->color:'#57534E' }}">{{ strtoupper(mb_substr($category->name,0,1)) }}</span><div class="min-w-0 flex-1"><h3 class="truncate text-sm font-semibold">{{ $category->name }}</h3><p class="text-xs text-stone-500">{{ $category->type->label() }}</p></div><p class="hidden text-xs text-stone-500 sm:block">{{ $category->transactions_count }} {{ Str::plural('transaction',$category->transactions_count) }} · {{ $category->budgets_count }} {{ Str::plural('budget',$category->budgets_count) }}</p><div x-data="{open:false}" class="relative" @click.outside="open=false"><button @click="open=!open" class="h-8 w-8 rounded-lg" aria-label="Actions for {{ $category->name }}">•••</button><div x-cloak x-show="open" class="absolute right-0 z-40 mt-1 w-40 rounded-xl border bg-[#fbf8f2] p-1 shadow-lg"><a href="{{ route('categories.edit',$category) }}" class="block rounded-lg px-3 py-2 text-sm">Edit</a><div class="border-t"></div><button wire:click="confirmDeletion('{{ $category->public_id }}')" @click="open=false" class="block w-full rounded-lg px-3 py-2 text-left text-sm text-red-700">Delete category</button></div></div></article>@endforeach</div>@endif
    </section>
    @if($deletingCategory)@php($target=$categories->firstWhere('public_id',$deletingCategory))<div class="fixed inset-0 z-50 flex items-center justify-center bg-stone-950/40 p-4"><div class="w-full max-w-md rounded-2xl bg-[#fbf8f2] p-6"><h2 class="text-lg font-semibold">Delete category?</h2><p class="mt-2 text-sm text-stone-600">You're about to permanently delete:</p><div class="mt-4 rounded-xl border p-4"><p class="font-semibold">{{ $target?->name }}</p><p class="text-sm text-stone-500">{{ $target?->type?->label() }}</p></div><p class="mt-3 text-xs text-stone-500">This is only possible if the category is unused by transactions, budgets, or recurring transactions.</p>@if($deletionError)<p class="mt-3 rounded-xl bg-red-50 p-3 text-sm text-red-700">{{ $deletionError }}</p>@endif<div class="mt-6 flex justify-end gap-2"><button wire:click="$set('deletingCategory',null)" class="rounded-xl border px-4 py-2.5">Cancel</button><button wire:click="delete" wire:loading.attr="disabled" class="rounded-xl bg-red-700 px-4 py-2.5 font-semibold text-white">Delete category</button></div></div></div>@endif
</div>
